[package]
edition = "2018"
license = "WTFPL"
name = "mercurial_stable_swap_n_pool_instructions"
publish = false
version = "0.1.0"

[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.10.25"
thiserror = "1.0.24"

[lib]
crate-type = ["lib"]
